# Generated by Django 3.1.4 on 2021-01-10 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.IntegerField()),
                ('lotsize', models.FloatField()),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateField(auto_now_add=True)),
                ('photo_main', models.ImageField(upload_to='uploads/%y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='uploads/%y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='uploads/%y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, upload_to='uploads/%y/%m/%d')),
                ('photo_4', models.ImageField(blank=True, upload_to='uploads/%y/%m/%d')),
                ('photo_5', models.ImageField(blank=True, upload_to='uploads/%y/%m/%d')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
