# Generated by Django 3.1.4 on 2021-01-10 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210110_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
